name: hello-world

on:
  pull_request:
    branches:
      - main

jobs:
  my-job:
    #name: My job name
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [1, 2]
        node2: [3, 4]
    steps:
      - name: my-step
        # https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
        run: echo "Hello World! ${{ matrix.node }} - ${{ matrix.node2 }}"
