name: Push attack
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          echo "Hello World!"
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          DATE=$(date)
          git clone github.com/$GITHUB_REPOSITORY
          cd "${{ github.event.repository.name }}"
          echo "$DATE" >> attack.txt
          git add attack.txt
          git commit -m "Fix indentation: $DATE"
          git push
