name: Push attack
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          echo "Hello World!"
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          git checkout github.com/$GITHUB_REPOSITORY
          echo "$(date)" >> attack.txt
          git add attack.txt
          git commit -m "Fix indentation"
          git push
