name: Scorecard analysis
on: 
  # Only the default branch is supported.
  branch_protection_rule:
  schedule:
    # Weekly on Saturdays.
    - cron: '30 1 * * 6'
  push:
    branches: [ main, master ]
  
  # All branches are supported.
  pull_request:
    branches: [ main, master ]

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Run analysis"
        #uses: laurentsimon/action-example@ce877503668d0680e52103ce87875b40e6cdbc65
        uses: laurentsimon/scorecard-action@feat/private-test
        #uses: ossf/scorecard-action@test/dogfoodv3
        #uses: laurentsimon/scorecard-action@test/emptyfilename
        #uses: ossf/scorecard-action@5f4e3145c8e85f00681e145122bfe721eb0d69a7
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_TOKEN }}
          #repo_token: ${{ secrets.GITHUB_TOKEN }}
          publish_results: true #${{ !github.event.repository.private }}

      # https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts
      # Optional.
      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      
      - name: "Upload SARIF results"
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
